/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClubRouteImport } from './routes/club'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardOutreachRouteImport } from './routes/dashboard.outreach'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard.onboarding'
import { Route as DashboardFollowUpRouteImport } from './routes/dashboard.follow-up'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutreachRoute = DashboardOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFollowUpRoute = DashboardFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/follow-up': typeof DashboardFollowUpRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/follow-up': typeof DashboardFollowUpRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/follow-up': typeof DashboardFollowUpRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/club'
    | '/dashboard'
    | '/dashboard/content'
    | '/dashboard/follow-up'
    | '/dashboard/onboarding'
    | '/dashboard/outreach'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/club'
    | '/dashboard/content'
    | '/dashboard/follow-up'
    | '/dashboard/onboarding'
    | '/dashboard/outreach'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/club'
    | '/dashboard'
    | '/dashboard/content'
    | '/dashboard/follow-up'
    | '/dashboard/onboarding'
    | '/dashboard/outreach'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClubRoute: typeof ClubRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/outreach': {
      id: '/dashboard/outreach'
      path: '/outreach'
      fullPath: '/dashboard/outreach'
      preLoaderRoute: typeof DashboardOutreachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/follow-up': {
      id: '/dashboard/follow-up'
      path: '/follow-up'
      fullPath: '/dashboard/follow-up'
      preLoaderRoute: typeof DashboardFollowUpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardFollowUpRoute: typeof DashboardFollowUpRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardOutreachRoute: typeof DashboardOutreachRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardContentRoute: DashboardContentRoute,
  DashboardFollowUpRoute: DashboardFollowUpRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardOutreachRoute: DashboardOutreachRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClubRoute: ClubRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
